### ISSUE TITLE
mdt_jobstats and ost_jobstats should be split for each jobstats metrics

### ISSUE THREAD

**Issue by sihara** [ScaleWX/barreleye#1]
following measurements are generated on tsdb after mdt_jobstats and ost_jobstats enabled. However, each measurement has unique jobid which causes very large cardinalities. we should avoid collecting unnecessary metrics and xml needs to be able to define each jobstat items in collected.conf e.g. only ost_jobstats_bytes and mdt_jobstats_samples
<pre>
mdt_jobstats_max
mdt_jobstats_min
mdt_jobstats_samples
mdt_jobstats_sum
mdt_jobstats_sumsq
ost_jobstats_bytes
ost_jobstats_max
ost_jobstats_min
ost_jobstats_samples
ost_jobstats_sum
ost_jobstats_sumsq
ost_stats_bytes
ost_stats_samples

**Comment by LiXi-storage** [comment]
We already has that feature on Collectd, but not ever widely used.

<pre>
#		Type "ost_jobstats"
#		<Rule>
#			Field "job_id"
#			Match "dd[.][[:digit:]]+"
#		</Rule>
		##Filter option can be used to discard some undesired fields.
#		<Filter>
#			Field "read_samples"
#			Field "read_bytes"
#			Field "write_samples"
#			Field "write_bytes"
#			Field "getattr"
#			Field "setattr"
#			Field "punch"
#			Field "sync"
#			Field "destroy"
#			Field "create"
#			Field "statfs"
#			Field "get_info"
#			Field "set_info"
#			Field "quotactl"
#		</Filter>
#	</Item>
</pre>

By adding filters to filter a name defined in lustre.xml file, we can define what fields should be removed when monitoring client is submitting the data to server.

When checking this feature of Collectd, I found a lot of errors of field name in Lustre XML files:

For example, in lustre-b_es5_2.xml:

```
<item>
 <name>ost_jobstats</name>
...
  <field>
    <index>1</index>
    <name>job_id</name>
...
  </field>
  <field>
    <index>2</index>
    <name>read_samples</name> # !!! **This is wrong, should be read_byte_samples**
...
  </field>
... # **the other names of the fields of this item look good.**
...
  <field>
    <index>6</index>
    <name>write_samples</name> # !!! **This is wrong, should be write_byte_samples**
...
  </field>
  <field>
    <index>10</index>
    <name>read</name> # !!! **This is wrong, should be read_samples**
...
  </field>
  <field>
    <index>11</index>
    <name>read</name> # !!! **This is wrong, should be read_samples_min**
...
  </field>
  <field>
    <index>12</index>
    <name>read</name> # !!! **This is wrong, should be read_samples_max**
...
  </field>
  <field>
    <index>13</index>
    <name>read</name> # !!! **This is wrong, should be read_samples_sum**
...
  </field>
```

There might be even more problem of names in the XML files.


We need to fix the XML files. To fix the XML files need to fix the M4 files. There might be a wrong macro defined in M4 files.

The reason of having broken XML without noticing it is, the names of the fields are not widely used or checked.

In collectd, we need to check that the name of field is unique in the item in function of filedata_xml_field_parse(). And quit with error if a name is duplicated for different fields. That will detect broken XML file.

**Comment by sihara** [comment]
Thanks Li Xi for pointing out. I wonder if "mdt_jobstats_xxxxxx_xxxxx" might be better name so that we can use '*' to Filter?
e.g. 
here is current name.
```
<index>2</index>
<name>open</name>
<type>number</type>
<first_value>0</first_value>
....
<index>3</index>
<name>open</name>
<type>number</type>
<first_value>0</first_value>
```
it would change
```
<index>2</index>
<name>mdt_jobstats_samples_open</name>
<type>number</type>
<first_value>0</first_value>
....
<index>3</index>
<name>mdt_jobstats_min_open</name>
<type>number</type>
<first_value>0</first_value>
```

in collectd.conf
```
    <Filter>
      Field mdt_jobstats_min_*
    </Filter>
```
Throught?

**Comment by sihara** [comment]
Oh, ost_jobstats are unique, but mdt_jobstats are not..

**Comment by sihara** [comment]
created new repo in [xml_definition](https://github.com/ScaleWX/xml_definition) and fixed filed name inlcuded.
